export const TAGS = {
  navike:      { label: 'Navike',       hue: 30  },
  fokus:       { label: 'Fokus',        hue: 250 },
  sistemi:     { label: 'Sistemi',      hue: 160 },
  psihologija: { label: 'Psihologija',  hue: 320 },
  strategija:  { label: 'Strategija',   hue: 200 },
  prodaja:     { label: 'Prodaja',      hue: 15  },
  liderstvo:   { label: 'Liderstvo',    hue: 280 },
  pisanje:     { label: 'Pisanje',      hue: 100 },
  odluke:      { label: 'Odluke',       hue: 60  },
  novac:       { label: 'Novac',        hue: 140 },
  proizvod:    { label: 'Proizvod',     hue: 220 },
  identitet:   { label: 'Identitet',    hue: 350 },
  kreativnost: { label: 'Kreativnost',  hue: 40  },
  biznis:      { label: 'Biznis',       hue: 180 },
  zivot:       { label: 'Život',        hue: 340 },
};

export const T = {
  appName: 'Znanje',
  appSubtitle: 'Lično · v2.4',
  nav: {
    home:     'Početna',
    library:  'Biblioteka',
    notebook: 'Sveska',
    ideas:    'Ideje',
    videos:   'Video lekcije',
    progress: 'Napredak',
    mindmaps: 'Mape uma',
  },
  common: {
    soon:           'Uskoro',
    search:         'Pretraži lekcije, knjige, ideje…',
    tweaks:         'Podešavanja',
    addBook:        'Dodaj knjigu',
    addIdea:        'Nova ideja',
    addVideo:       'Dodaj video',
    addLesson:      'Dodaj lekciju',
    editWithAI:     'Uredi pomoću AI',
    save:           'Sačuvaj',
    cancel:         'Otkaži',
    close:          'Zatvori',
    delete:         'Obriši',
    confirmDelete:  'Sigurno?',
    logout:         'Odjavi se',
    all:            'Sve',
    fromBooks:      'Iz knjiga',
    fromNotebook:   'Iz sveske',
    shuffle:        'Promešaj',
    recent:         'Skorašnje',
    title:          'Naslov',
    author:         'Autor',
    read:           'Pročitano',
    reading:        'Čitam',
    finished:       'Završeno',
    pages:          'strana',
    pagesRead:      'pročitane strane',
    day:            'dan',
    days:           'dana',
    backTo:         'Nazad',
    library:        'Biblioteka',
    aiBadgeNote:    'Generisano · Nisu reči autora',
    aiSummary:      'AI sažetak',
    themes:         'Teme',
    fiveKeyIdeas:   'Pet ključnih ideja',
    myLessons:      'Moje lekcije',
    myNotes:        'Moje beleške',
    noLessons:      'Još nema lekcija',
    noLessonsBody:  'Zabeleži prve uvide iz ove knjige.',
    addFirstLesson: 'Dodaj prvu lekciju',
    notesPlaceholder: 'Počni da kucaš — reakcije, pitanja, veze sa drugim knjigama…',
    watchVideo:     'Pogledaj video',
    views:          'pregleda',
    duration:       'Trajanje',
    recorded:       'Snimljeno',
    uploadNew:      'Dodaj video',
    describeIdea:   'Opiši svoju ideju',
    notebookTitle:  'Sveska',
    notebookSubtitle: 'Ideje koje ne pripadaju jednoj knjizi — zapažanja, veze, pitanja.',
    ideasTitle:     'Ideje',
    ideasSubtitle:  'Stvari koje ti padnu na pamet. Klikni na bilo koju da pogleдаš ili izmeniš.',
    videosTitle:    'Moje video lekcije',
    videosSubtitle: 'Tvoji snimci — uvek su sa tobom.',
    progressTitle:  'Napredak · 2026',
    progressHero:   'Tiha navika,',
    progressHeroSub:'koja se ukamaćuje.',
    today:          'Danas',
    thisMonth:      'Ovaj mesec',
    thisYear:       'Ove godine',
    activity:       'Aktivnost',
    last6Months:    'Poslednjih 6 meseci',
    goal:           'Cilj',
    onPace:         'Na ritmu za',
    ahead:          'ispred plana',
    books:          'knjiga',
    booksDone:      'Završene knjige',
    booksOf:        (a, b) => `${a} od ${b} knjiga`,
    streak:         'dana zaredom',
    lessonsCaptured:'Ukupno lekcija',
    thisQuarter:    'Ukupno',
    vsLastQ:        'od poslednjeg puta',
    readingTime:    'Knjige u toku',
    dailyAvg:       'Trenutno čitam',
    minPerDay:      'knjiga',
    topSource:      'Najcitiranije',
    mostCited:      'Knjiga sa najviše lekcija',
    highlights:     'lekcija',
    mostRevisited:  'Teme:',
    less:           'Manje',
    more:           'Više',
    mon: 'pon', wed: 'sre', fri: 'pet',
    months:         ['nov','dec','jan','feb','mar','apr'],
    heroLine1:      'Sve što si naučio,',
    heroLine2:      'jedna po jedna misao.',
    lessonsCount:   'lekcija',
    booksCount:     'knjiga',
    currentlyReading: 'Trenutno čitam',
    theShelf:       'Polica',
    searchLibrary:  'Pretraži naslov ili autora…',
    selectTag:      'Kategorija',
    selectBook:     'Poveži sa knjigom (opciono)',
    noData:         'Nema sadržaja',
    addFirst:       'Dodaj prvi unos',
    emptyLibrary:   'Biblioteka je prazna',
    emptyLibraryBody: 'Dodaj prvu knjigu.',
    emptyLessons:   'Nema lekcija',
    emptyLessonsBody: 'Dodaj svoju prvu lekciju iz knjige ili razmišljanja.',
    emptyIdeas:     'Nema ideja',
    emptyIdeasBody: 'Zabeleži prvu ideju dok ti je još sveža.',
    emptyVideos:    'Nema video snimaka',
    emptyVideosBody:'Dodaj link ili opis prvog video.',
    emptyNotebook:  'Sveska je prazna',
    emptyNotebookBody: 'Počni da zapisuješ slobodne misli.',
  },
};
